version: '3'
services:
    opencart:
      image: vimagick/opencart
      ports:
        - "8000:80"
      links:
        - mysql
      restart: always

    mysql:
      image: mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=opencart
      restart: always
